import Head from 'next/head';
import Dashboard from './dashboard';

export default function Home() {
    return (
        <div>
            <Head>
                <title>Next Js</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/vercel.svg" />
            </Head>
            
            <Dashboard/>
        </div>
    )
}

